### ISSUE TITLE
MySQL provider - keep connection

### ISSUE THREAD

**Issue by Bizzonium** [MrNavaStar/InvSync#21] opened 2022-05-29 16:56 UTC
Tried to manually create schema for MySQL provider. Works ok. Sometimes got log spam with these. Propable solution is to keep connection openned.
```log
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1648)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1564)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at mrnavastar.sqlib.util.SqlManager.readJson(SqlManager.java:137)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at mrnavastar.sqlib.api.DataContainer.putIntoDatabase(DataContainer.java:56)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at mrnavastar.sqlib.api.DataContainer.put(DataContainer.java:116)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at mrnavastar.invsync.util.Converter.savePlayerData(Converter.java:101)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at mrnavastar.invsync.InvSync.lambda$onInitialize$1(InvSync.java:57)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:140)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at net.minecraft.class_2535.handler$cpg000$handleDisconnect(class_2535.java:1089)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at net.minecraft.class_2535.channelInactive(class_2535.java)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:762)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:568)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	at com.mysql.cj.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:1579)
[16:44:55] [Netty Epoll Server IO #4/INFO]: [STDERR]: 	... 45 more
```

**Comment by Bizzonium** [comment] 2022-05-29 17:00
![image](https://user-images.githubusercontent.com/8555356/170882377-79d4e2dd-a078-4e85-bbd3-98e6a9fec3fb.png)

**Comment by MrNavaStar** [comment] 2022-05-30 03:50
Huh, that's weird. It should set the up table itself. Keeping the connection open won't work because it will lock up for any other transaction. Does it work fine despite these errors?

**Comment by Bizzonium** [comment] 2022-05-30 12:02
No, server hangs

**Comment by MrNavaStar** [comment] 2022-05-30 18:56
Oh, that's not good! Does this happen every time you switch servers or just occasionally?

**Comment by Bizzonium** [comment] 2022-06-04 21:08
> Oh, that's not good! Does this happen every time you switch servers or just occasionally?

Just occasionally. Also i suggest to implement some features from HuskSync https://www.spigotmc.org/resources/husksync-1-16-1-17-1-18-synchronize-player-inventories-data-cross-server.97144/ . That would be sweet but i understand it would be much harder and time-costly

**Comment by MrNavaStar** [comment] 2022-06-05 03:17
Sorry the link doesn't work for me. Could you please request specific things? Maybe make a new issue for them also. 

Im not really sure what to do about the issue here tho. The error doesn't really have much useful. You said you manually created all the columns in the table? Why?

**Comment by Bizzonium** [comment] 2022-06-05 05:02
> Sorry the link doesn't work for me. Could you please request specific things? Maybe make a new issue for them also.

https://github.com/WiIIiam278/HuskSync yeap, definitly out of scope of this issue

> Im not really sure what to do about the issue here tho. The error doesn't really have much useful. You said you manually created all the columns in the table? Why?

I don't remember exactly why. Maybe i encountered issue and thought it's the safest and quickest way. Maybe i should close this issue until i get more info about what's going on.

**Comment by MrNavaStar** [comment] 2022-06-06 07:14
You can leave it open, but yeah I don't really have a lot to go on with this. Maybe you could try setting up a test server and see if you can reproduce the issue? Again the database should set it self up, so if that's not working there might be other things that need to be fixed.

**Comment by Bizzonium** [comment] 2022-06-06 13:30
>  Again the database should set it self up

Checked it again, no issues. It works.

**Comment by MrNavaStar** [comment] 2022-06-10 20:27
So is this issue no longer a problem?

**Comment by Bizzonium** [comment] 2022-06-11 17:02
```
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]: java.sql.SQLException: No operations allowed after statement closed.
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:82)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.StatementImpl.setQueryTimeout(StatementImpl.java:1896)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at mrnavastar.sqlib.util.SqlManager.endTransaction(SqlManager.java:62)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at mrnavastar.sqlib.api.databases.Database.endTransaction(Database.java:28)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at mrnavastar.sqlib.api.Table.endTransaction(Table.java:55)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at mrnavastar.invsync.InvSync.lambda$onInitialize$1(InvSync.java:58)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$4(ServerPlayConnectionEvents.java:59)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.invokeDisconnectEvent(ServerPlayNetworkAddon.java:140)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at net.fabricmc.fabric.impl.networking.AbstractNetworkAddon.handleDisconnect(AbstractNetworkAddon.java:131)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at net.minecraft.class_2535.handler$ejj000$handleDisconnect(class_2535.java:1590)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at net.minecraft.class_2535.channelInactive(class_2535.java)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:831)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at java.base/java.lang.Thread.run(Unknown Source)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]: Caused by: com.mysql.cj.exceptions.StatementIsClosedException: No operations allowed after statement closed.
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Unknown Source)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:85)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.StatementImpl.checkClosed(StatementImpl.java:336)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  at com.mysql.cj.jdbc.StatementImpl.setQueryTimeout(StatementImpl.java:1889)
[17:00:39] [Netty Epoll Server IO #20/INFO]: [STDERR]:  ... 43 more
```

**Comment by MrNavaStar** [comment] 2022-06-12 23:00
Okay so this is still an issue

**Comment by michiruf** [comment] 2022-12-28 23:43
This happens for me reproducable, if I have 2 servers up and running, and then afterwards installing the InvSync mod. It does not happen on newly created server instances when the mod is already installed.

Tested on 1.19.2 and with both SQLITE and MySQL

**Comment by MrNavaStar** [comment] 2022-12-29 00:50
Ah interesting. I'm not sure adding support for pre-existing servers is really a viable option however. How is the system supposed to know which server to sync items from? On a clean install it doesn't matter, cause both servers are blank. But on used ones one server needs to be over written. I'm guessing this has something to do with the issue, but I'm not sure how to go about resolving it. 

Non the less Thank you for the reproduction steps, I will give them a try and see what I can come up with.

**Comment by michiruf** [comment] 2022-12-29 16:14
If you push your latest changes, I can have a look too and figure out what might be causing this issue, if you want to

**Comment by MrNavaStar** [comment] 2023-01-16 17:00
Same issue as #54

**Comment by MrNavaStar** [comment] 2023-01-16 19:55
Fixed in new release

**Closed as completed by MrNavaStar** 2023-01-16 19:55 UTC
Labels: bug
